/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burjalarab_techno;

/**
 *
 * @author Sony
 */
public class Activities extends javax.swing.JFrame {

    /**
     * Creates new form Activities
     */
    public Activities() {
        initComponents();
    }
    int choice=1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Facilities And Activities For Guests! ");

        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setText(">");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton2.setText("<");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/restaurant.PNG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(10);
        jTextArea1.setText("In our nine signature restaurants and bars, dining is about far more than food. We specialise in bringing together every element to ensure your experience is exceptional. Soak up the vibrant atmosphere in our elegant spaces, dotted through Burj Al Arab from the atrium all the way to the skyline.\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apply For The Facility :");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Al-Muntaha Restaurant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1)
                                .addGap(18, 33, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jTextArea1.setLineWrap(true);
       jTextArea1.setWrapStyleWord(true);
        if(choice >=1 && choice <8)
           choice++;
       else 
           ;
           switch(choice)
    {
            case 1:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/restaurant.PNG")));
                     jLabel3.setText("Al-Muntaha Restaurant");
                     jTextArea1.setText("In our nine signature restaurants and bars, dining is about far more than food. We specialise in bringing together every element to ensure your experience is exceptional. Soak up the vibrant atmosphere in our elegant spaces, dotted through Burj Al Arab from the atrium all the way to the skyline.");
                    
                     break;
            case 2:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/butler.PNG")));
                     jLabel3.setText("24/7 Butler Service");
                     jTextArea1.setText("For the comfort and convenience of guests, there is a dedicated reception on each floor with check-in conducted in the privacy of the individual suite. Butlers are in attendance 24 hours a day to address the needs of each and every guest.");
                     break;
            case 3:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/carRental.PNG")));
                     jLabel3.setText("Dream Car Rental");
                     jTextArea1.setText("Take in life from the fast lane. Our fleet of luxury cars is available for private hire, and offers unsurpassed auto-mobiles. Glide the streets of Dubai in the world's most exclusive cars, including models from Aston Martin, Ferrari and Lamborghini. For a touch of old world glamour, classic cars tempt with an understated elegance that even today is rarely matched.");
                     break;
            case 4:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/fitness.PNG")));
                     jLabel3.setText("Talise Fitness Club, Gym And Spa");
                     jTextArea1.setText("With premium mixed fitness and spa facilities and exceptional dedicated ladies only fitness and spa facilities, Talise Fitness at Burj Al Arab is the prestigious club where you can indulge yourself while achieving your aspirations.");
                     break;
            case 5:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/facil1.PNG")));
                     jLabel3.setText("Helicopter Pickup");
                     jTextArea1.setText("Guests may arrive at Dubai's most iconic hotel by either one of the world's largest chauffeur-driven fleets of Rolls Royce's or by a dedicated helicopter transfer service. Visitors who arrive by helicopter will experience a 7 to 10 minute birds-eye-view of the city, culminating in a dramatic landing on the hotel's helipad on the 28th level.");
                     break;
            case 6:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/pool.PNG")));
                     jLabel3.setText("Snooker Table In Suites");
                     jTextArea1.setText("Special Facilities Include"
                             + "\n"+"Complimentary Wi-Fi, a 21-inch iMac, a range of 42-inch and 32-inch widescreen interactive HD TVs, Bose iPod/iPhone docking station and media hub, remote controlled environment including curtains, TV, en-suite music and lights and a private all in one printer, copier, scanner and fax.");
                     break; 
            case 7:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/Yacht.PNG")));
                     jLabel3.setText("Sightseeing in Your Personal Yacht");
                     jTextArea1.setText("See the Burj Al Arab iconic sail shape from the Arabian Gulf with a private yacht charter service available exclusively to our guests. Offering the height of indulgence, you and your guests will enjoy total privacy, and the services of our skilled, attentive onboard team (comprising a butler, hostess and chef). For added relaxation, a spa therapist can also join you on board to provide luxury pampering treatments.");
                     break;
            case 8:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/wildwadi.PNG")));
                     jLabel3.setText("The Wild Wadi Waterpark");
                     jTextArea1.setText("One of the world's most impressive waterparks, Wild Wadi is a playground that is guaranteed to delight both the young and the young at heart. It is the perfect location for leisure, as well as special events such as team building, business functions and employee incentive schemes.");
                     break;         
    }         
    
    }//GEN-LAST:event_jButton1MouseEntered

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
       jTextArea1.setLineWrap(true);
       jTextArea1.setWrapStyleWord(true);
        if(choice >1 && choice <=8)
           choice--;
       else 
           ;
           switch(choice)
    {
            case 1:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/restaurant.PNG")));
                     jLabel3.setText("Al-Muntaha Restaurant");
                     jTextArea1.setText("In our nine signature restaurants and bars, dining is about far more than food. We specialise in bringing together every element to ensure your experience is exceptional. Soak up the vibrant atmosphere in our elegant spaces, dotted through Burj Al Arab from the atrium all the way to the skyline.");
                    
                     break;
            case 2:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/butler.PNG")));
                     jLabel3.setText("24/7 Butler Service");
                     jTextArea1.setText("For the comfort and convenience of guests, there is a dedicated reception on each floor with check-in conducted in the privacy of the individual suite. Butlers are in attendance 24 hours a day to address the needs of each and every guest.");
                     break;
            case 3:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/carRental.PNG")));
                     jLabel3.setText("Dream Car Rental");
                     jTextArea1.setText("Take in life from the fast lane. Our fleet of luxury cars is available for private hire, and offers unsurpassed auto-mobiles. Glide the streets of Dubai in the world's most exclusive cars, including models from Aston Martin, Ferrari and Lamborghini. For a touch of old world glamour, classic cars tempt with an understated elegance that even today is rarely matched.");
                     break;
            case 4:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/fitness.PNG")));
                     jLabel3.setText("Talise Fitness Club, Gym And Spa");
                     jTextArea1.setText("With premium mixed fitness and spa facilities and exceptional dedicated ladies only fitness and spa facilities, Talise Fitness at Burj Al Arab is the prestigious club where you can indulge yourself while achieving your aspirations.");
                     break;
            case 5:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/facil1.PNG")));
                     jLabel3.setText("Helicopter Pickup");
                     jTextArea1.setText("Guests may arrive at Dubai's most iconic hotel by either one of the world's largest chauffeur-driven fleets of Rolls Royce's or by a dedicated helicopter transfer service. Visitors who arrive by helicopter will experience a 7 to 10 minute birds-eye-view of the city, culminating in a dramatic landing on the hotel's helipad on the 28th level.");
                     break;
            case 6:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/pool.PNG")));
                     jLabel3.setText("Snooker Table In Suites");
                     jTextArea1.setText("Special Facilities Include"
                             + "\n"+"Complimentary Wi-Fi, a 21-inch iMac, a range of 42-inch and 32-inch widescreen interactive HD TVs, Bose iPod/iPhone docking station and media hub, remote controlled environment including curtains, TV, en-suite music and lights and a private all in one printer, copier, scanner and fax.");
                     break; 
            case 7:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/Yacht.PNG")));
                     jLabel3.setText("Sightseeing in Your Personal Yacht");
                     jTextArea1.setText("See the Burj Al Arab iconic sail shape from the Arabian Gulf with a private yacht charter service available exclusively to our guests. Offering the height of indulgence, you and your guests will enjoy total privacy, and the services of our skilled, attentive onboard team (comprising a butler, hostess and chef). For added relaxation, a spa therapist can also join you on board to provide luxury pampering treatments.");
                     break;
            case 8:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/wildwadi.PNG")));
                     jLabel3.setText("The Wild Wadi Waterpark");
                     jTextArea1.setText("One of the world's most impressive waterparks, Wild Wadi is a playground that is guaranteed to delight both the young and the young at heart. It is the perfect location for leisure, as well as special events such as team building, business functions and employee incentive schemes.");
                     break;          
    }
    }//GEN-LAST:event_jButton2MouseEntered
      
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
