/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burjalarab_techno;


import AppPackage.AnimationClass;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.Timer;
import java.sql.*;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sony
 */
public class Activities1 extends javax.swing.JFrame {

    /**
     * Creates new form Activities
     */
    public Activities1() {
        initComponents();
        setFocusable(true);
        requestFocusInWindow();
    }
    int choice=1;
    Timer panel  = new Timer(50,new Panel());
    static int ch;
    int[] price = new int[8];
    static int red = 0,green =0,blue=0;
    static float totprice = 0.0f;
    int[] actArr = {0,0,0,0,0,0,0,0};
    static int a1 = 0,a2 = 0,a3 = 0,a4 = 0,a5 = 0,a6 = 0,a7 = 0,a8 = 0;
    String[] activity = new String[8];
    Timer tech = new Timer(50, new Techno());
    static String user = "";
    static String pass = "";
    static String act = "";
    static int x = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public class Techno implements ActionListener { 
        public void actionPerformed(ActionEvent evt) {
            
        }
    }
    public class Panel implements ActionListener{
    public void actionPerformed(ActionEvent evt) {
        Color();
        if(red == 255 && green == 255 && blue == 255)
            ch = 1;
        if(red == 0 && green == 0 && blue == 0)
            ch = 0;
        jPanel1.setBackground(new java.awt.Color(red, green, blue));
    }
    }
    public void Color(){
        if(ch == 0)
            if(green == 255)
        {
           if(green==255 && red ==255)
           {
           green =255;
           red=255;
           blue++;          
           }
           else
           {   
            green= 255;
           red++;
           }
        }
        else
            green++;
        if(ch == 1)
            if(green == 0)
        {
           if(green==0 && red ==0)
           {
           red =0;
           green=0;
           blue--;          
           }
           else
           {   
            green = 0;
           red--;
           }
        }
        else
            green--;
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setMaximumSize(new java.awt.Dimension(661, 550));
        jFrame1.setMinimumSize(new java.awt.Dimension(661, 550));
        jFrame1.setPreferredSize(new java.awt.Dimension(661, 550));
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame1WindowOpened(evt);
            }
        });
        jFrame1.getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Burj Al Arab Activity Arena");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 79);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jFrame1.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 79, 660, 10);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        jButton5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jButton5.setText("Book Facilities");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(50, 450, 210, 50);

        jLabel10.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Selected Activities :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 0, 303, 39);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel6.setText("Total Price :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 220, 120, 40);

        jLabel11.setFont(new java.awt.Font("CordiaUPC", 0, 20)); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(160, 220, 130, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Activity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 50, 270, 138);

        jFrame1.getContentPane().add(jPanel3);
        jPanel3.setBounds(350, 90, 300, 400);

        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        jLabel7.setText("User ID");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(16, 98, 130, 41);

        jLabel8.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        jLabel8.setText("Password");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(16, 151, 141, 41);

        jTextField1.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jPanel2.add(jTextField1);
        jTextField1.setBounds(163, 98, 160, 40);

        jTextField2.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jPanel2.add(jTextField2);
        jTextField2.setBounds(163, 151, 160, 40);

        jLabel9.setFont(new java.awt.Font("CordiaUPC", 1, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Login");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(73, 15, 189, 40);

        jButton4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(94, 230, 150, 44);

        jLabel12.setFont(new java.awt.Font("CordiaUPC", 3, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel12);
        jLabel12.setBounds(16, 450, 318, 49);

        jFrame1.getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 90, 330, 400);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Activities");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Facilities And Activities");
        jLabel5.setFocusable(false);

        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setText(">");
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton2.setText("<");
        jButton2.setFocusable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/restaurant.PNG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel1.setFocusable(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(10);
        jTextArea1.setText("In our nine signature restaurants and bars, dining is about far more than food. We specialise in bringing together every element to ensure your experience is exceptional. Soak up the vibrant atmosphere in our elegant spaces, dotted through Burj Al Arab from the atrium all the way to the skyline.\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setEnabled(false);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apply For The Facility :");

        jCheckBox1.setFocusable(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Al-Muntaha Restaurant");
        jLabel3.setFocusable(false);

        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setText(" Book Facilities");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setLayout(int ch) {
            
        
        switch(ch)
        {
            case 1:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/restaurant.PNG")));
                     jLabel3.setText("Al-Muntaha Restaurant");
                     jTextArea1.setText("In our nine signature restaurants and bars, dining is about far more than food. We specialise in bringing together every element to ensure your experience is exceptional. Soak up the vibrant atmosphere in our elegant spaces, dotted through Burj Al Arab from the atrium all the way to the skyline.");
                     break;
            case 2:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/butler.PNG")));
                     jLabel3.setText("24/7 Butler Service");
                     jTextArea1.setText("For the comfort and convenience of guests, there is a dedicated reception on each floor with check-in conducted in the privacy of the individual suite. Butlers are in attendance 24 hours a day to address the needs of each and every guest.");
                     break;
            case 3:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/carRental.PNG")));
                     jLabel3.setText("Dream Car Rental");
                     jTextArea1.setText("Take in life from the fast lane. Our fleet of luxury cars is available for private hire, and offers unsurpassed auto-mobiles. Glide the streets of Dubai in the world's most exclusive cars, including models from Aston Martin, Ferrari and Lamborghini. For a touch of old world glamour, classic cars tempt with an understated elegance that even today is rarely matched.");
                     break;
            case 4:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/fitness.PNG")));
                     jLabel3.setText("Talise Fitness Club, Gym And Spa");
                     jTextArea1.setText("With premium mixed fitness and spa facilities and exceptional dedicated ladies only fitness and spa facilities, Talise Fitness at Burj Al Arab is the prestigious club where you can indulge yourself while achieving your aspirations.");
                     break;
            case 5:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/facil1.PNG")));
                     jLabel3.setText("Helicopter Pickup");
                     jTextArea1.setText("Guests may arrive at Dubai's most iconic hotel by either one of the world's largest chauffeur-driven fleets of Rolls Royce's or by a dedicated helicopter transfer service. Visitors who arrive by helicopter will experience a 7 to 10 minute birds-eye-view of the city, culminating in a dramatic landing on the hotel's helipad on the 28th level.");
                     break;
            case 6:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/pool.PNG")));
                     jLabel3.setText("Snooker Table In Suites");
                     jTextArea1.setText("Special Facilities Include"
                             + "\n"+"Complimentary Wi-Fi, a 21-inch iMac, a range of 42-inch and 32-inch widescreen interactive HD TVs, Bose iPod/iPhone docking station and media hub, remote controlled environment including curtains, TV, en-suite music and lights and a private all in one printer, copier, scanner and fax.");
                     break; 
            case 7:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/Yacht.PNG")));
                     jLabel3.setText("Sightseeing in Your Personal Yacht");
                     jTextArea1.setText("See the Burj Al Arab iconic sail shape from the Arabian Gulf with a private yacht charter service available exclusively to our guests. Offering the height of indulgence, you and your guests will enjoy total privacy, and the services of our skilled, attentive onboard team including a butler, hostess and chef.");
                     break;
            case 8:  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/wildwadi.PNG")));
                     jLabel3.setText("The Wild Wadi Waterpark");
                     jTextArea1.setText("One of the world's most impressive waterparks, Wild Wadi is a playground that is guaranteed to delight both the young and the young at heart. It is the perfect location for leisure, as well as special events such as team building, business functions and employee incentive schemes.");
                     break;
        }
        }
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jTextArea1.setLineWrap(true);
       jTextArea1.setWrapStyleWord(true);
        if(choice >1 && choice <=8)
           choice--;
        
        setLayout(choice);
        if(actArr[choice-1] == 1) 
            jCheckBox1.setSelected(true);
        else 
            jCheckBox1.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
       
    }//GEN-LAST:event_jButton2MouseEntered

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        int ch = choice - 1;
        if(jCheckBox1.isSelected() == true)
            actArr[ch] = 1;
        else if(jCheckBox1.isSelected() == false)
            actArr[ch] = 0;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int arr[] = {0,0,0,0,0,0,0,0};
        
        if(Arrays.equals(actArr,arr))
            JOptionPane.showMessageDialog(null," Please Select Atleast One Category To Avail... ");
        else
        { 
            jFrame1.setVisible(true);
            jFrame1.setSize(661, 523);
            for(int i = 0;i< 8;i++)
                if(actArr[i] == 1)
                   activity[i] = "Y";
                else 
                   activity[i] = "N";
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int i = 0;i<8;i++)
        {
             if(activity[i].equals("Y"))
             {
                switch(i)
                        {
                             case 0 : model.addRow(new Object[]{"Restaurant","400 AED"});
                             a1=1;
                             price[0]=400;
                             break;
                             case 1 : model.addRow(new Object[]{"Butler Service","200 AED"});
                             a2=1;
                             price[1]=200;
                             break;
                             case 2 : model.addRow(new Object[]{"Dream Car Rental","2000 AED"});
                             price[2]=2000;
                             a3=1;
                             break;
                             case 3 : model.addRow(new Object[]{"Talise Gym ","700 AED"});
                             price[3]=700;
                             a4=1;
                             break;
                             case 4 : model.addRow(new Object[]{"Helicopter Pickup","1000 AED"});
                             price[4]=1000;
                             a5=1;
                             break;
                             case 5 : model.addRow(new Object[]{"Snooker Table","300 AED"});
                             price[5]=300;
                             a6=1;
                             break;
                             case 6 : model.addRow(new Object[]{"Personal Yacht Service","2500 AED"});
                             a7=1;
                             price[6]=2500;
                             break;
                             case 7 : model.addRow(new Object[]{"Wild Wadi Waterpark","500 AED"});
                             a8=1;
                             price[7]=500;
                             break;
                        }
             
             }
        }
        for(int i = 0;i<8;i++)
            totprice+=price[i];
        jLabel11.setText(" "+totprice+" AED");
        panel.start();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        user = jTextField1.getText();
        pass = jTextField2.getText();
        
        String namelabel;
        AnimationClass AC  = new AnimationClass();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM CHECKIN WHERE user = '"+user+"' AND pass = '"+pass+"'");
            if(res.next())
            {
              namelabel = res.getString("name");
              AC.jButtonYUp(450,350, 10, 10, jButton5);
              jLabel12.setText("Hello Mr. "+namelabel);
              jButton4.setText("Welcome!");
              jButton4.setForeground(new java.awt.Color(51, 201, 51));
              jButton4.setEnabled(false);
              AC.jLabelYUp(450,350,10,10,jLabel12);
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jFrame1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowOpened
        

    }//GEN-LAST:event_jFrame1WindowOpened

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        insert();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       jTextArea1.setLineWrap(true);
       jTextArea1.setWrapStyleWord(true);
        if(choice >=1 && choice <8)
           choice++;
        
        setLayout(choice);
        if(actArr[choice-1] == 1) 
            jCheckBox1.setSelected(true);
        else 
            jCheckBox1.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == 39){
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
             if(choice >=1 && choice <8)
                choice++;

             setLayout(choice);
             if(actArr[choice-1] == 1) 
                 jCheckBox1.setSelected(true);
             else 
                 jCheckBox1.setSelected(false);
        } else if(evt.getKeyCode() == 37) {
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
             if(choice >1 && choice <=8)
                choice--;

             setLayout(choice);
             if(actArr[choice-1] == 1) 
                 jCheckBox1.setSelected(true);
             else 
                 jCheckBox1.setSelected(false);
        }
            
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased
    public void insert()
    {
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta1 = con.createStatement();
            int i = sta1.executeUpdate("INSERT INTO ACTIVITY VALUES ('"+user+"','"+pass+"',"+a1+","+a2+","+a3+","+a4+","+a5+","+a6+","+a7+","+a8+","+totprice+")");
            if(i > 0) {
                JOptionPane.showMessageDialog(null,"The Activities you Selected, are ready to be availed. For details and more information, contact Bell Desk at Your Floor or at the Reception. ");
                jButton5.setText("Booked");
                jButton5.setEnabled(false);
                jButton5.setForeground(new java.awt.Color(51, 201, 51));
            }
            else 
                JOptionPane.showMessageDialog(null," System Error.... ");
               
        }
        catch(Exception e)
        {
            
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activities1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activities1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activities1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activities1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activities1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
