/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burjalarab_techno;

import AppPackage.AnimationClass;
import static burjalarab_techno.Activities1.red;
import static burjalarab_techno.Activities1.user;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.lang.String;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static oracle.jrockit.jfr.events.Bits.longValue;

/**
 *
 * @author Sony
 */
public class checkout1 extends javax.swing.JFrame {

    /**
     * Creates new form checkout
     */
    public checkout1() {
        initComponents();
    }
    static int c = 1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    static String namelabel="";
    Timer tech = new Timer(50,new tech());
    DefaultTableModel mod;
    Timer panel  = new Timer(50,new Panel());
    static int i = 0;
    static int ch;
    static int red = 255,green=255,blue=255;
    static String str = "Burj Al Arab Customer Lounge";
    static String str1 = "";
    Timer time = new Timer(250,new time());
    static int time1 = 0;
    String s1 = "";
    float checkPrice,actPrice,terrPrice,tourPrice,finPrice,conPrice;
    static String user="",pass=""; 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(835, 490));
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame1WindowOpened(evt);
            }
        });
        jFrame1.getContentPane().setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img1.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 70, 280, 370);

        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 480, 280, 370);

        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(10, -370, 280, 370);

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(310, 90, 120, 60);

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setText("Activities");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(440, 90, 110, 60);

        jButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton5.setText("Tourism ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(690, 90, 120, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        jFrame1.getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 160, 510, 190);

        jButton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton6.setText("Terrace");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton6);
        jButton6.setBounds(560, 90, 120, 60);

        jLabel6.setFont(new java.awt.Font("CordiaUPC", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Burj Al Arab");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jFrame1.getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 850, 60);

        jButton4.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        jButton4.setText("Finalize Transaction");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(380, 370, 370, 70);

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setMinimumSize(new java.awt.Dimension(500, 437));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(250, 250, 250));
        jLabel10.setFont(new java.awt.Font("CordiaUPC", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Burj Al Arab");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total Price");

        jLabel12.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N

        jLabel13.setFont(new java.awt.Font("CordiaUPC", 2, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Convert to");

        jComboBox1.setFont(new java.awt.Font("CordiaUPC", 3, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US Dollar", "Indian Rupee", "Australian Dollar", "British Pounds", "BitCoin", "Chinese Yuan", "Iraqi Dinar", "Japanese Yen", "North Korean Won", "Swiss Franc", "Thai Baht" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("CordiaUPC", 1, 18)); // NOI18N
        jLabel14.setText("Total Cost");

        jLabel15.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(675, 527));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("CordiaUPC", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("____________________________");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(630, 6, 612, 51);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -1, 670, 70);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("We believe you had a great time staying with us. Please come back soon to give us an oppportunity to serve you again.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(320, 0, 294, 180);

        jLabel3.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 180, 180, 40);

        jLabel4.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("User ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 230, 108, 42);

        jLabel5.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 280, 108, 41);

        jTextField1.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 230, 168, 42);

        jTextField2.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(140, 280, 168, 41);

        jButton1.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jButton1.setText("Checking...");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 340, 208, 39);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 90, 310, 380);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/Image 2.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 660, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AnimationClass AC = new AnimationClass();
        AC.jLabelXLeft(630,20, 10,10, jLabel1);
        tech.start();        
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jTextField2.setText(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        user = jTextField1.getText();
        pass = jTextField2.getText();
        String user1,user2;
        user1=user2="";
        AnimationClass AC  = new AnimationClass();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM CHECKIN WHERE user = '"+user+"'");
        if(res.next())
        {  
           time.start();
           jTextField2.setEnabled(true);
           jTextField1.setEnabled(false);
            jButton1.setForeground(new java.awt.Color(51, 201, 51));
            jButton1.setText("Used ID Accepted!");
           
        }
        res.close();
        sta.close();
        con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
           
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        AnimationClass AC = new AnimationClass();
        user = jTextField1.getText();
        pass = jTextField2.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM CHECKIN WHERE pass = '"+pass+"'");
        String name="";
            if(res.next())
        {
           AC.jTextAreaXLeft(320, 10, 10, 10, jScrollPane1);
           name=res.getString("name");
           jTextArea1.setText("Thank You Mr. "+name+" \nWe hope you had a great time staying with us. Please come back soon to give us an oppportunity to serve you again.");
           jButton1.setEnabled(true);
           jTextField2.setEnabled(false);
           jButton1.setText("Check Details");
           jButton1.setForeground(new java.awt.Color(51, 201, 51));
        }
            res.close();
        sta.close();
        con.close();
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
           
        
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFrame1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowOpened
        AnimationClass AC = new AnimationClass();
          new Thread() {
          @Override
            public void run(){
            try {
                while(true)
                { 
                  switch(c)
                  {
                      case 1 :   Thread.sleep(2000);
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelXLeft(10,-290, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img2.png")));
                                 AC.jLabelYDown(-370, 70, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=2;
                                 break;
                      case 2 :   Thread.sleep(2000);
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYUp(70,-370, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img3.png")));
                                 AC.jLabelYUp(480, 70, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3,3,3,3, new java.awt.Color(0, 0, 0)));
                                 c=3;
                                 break;
                      case 3 :   Thread.sleep(2000);
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYDown(70,480, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img4.png")));
                                 AC.jLabelXRight(-290, 10, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=4;
                                 break;
                       case 4 :   Thread.sleep(2000);
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelXLeft(10,-290, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img5.png")));
                                 AC.jLabelYDown(-370, 70, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=5;
                                 break;
                      case 5 :   Thread.sleep(2000); 
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYUp(70,-370, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img6.png")));
                                 AC.jLabelYUp(480, 70, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3,3,3,3, new java.awt.Color(0, 0, 0)));
                                 c=6;
                                 break;
                      case 6 :   Thread.sleep(2000);
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYDown(70,480, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img7.png")));
                                 AC.jLabelXRight(-290, 10, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=7;
                                 break;
                       case 7 :  Thread.sleep(2000);
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); 
                                 AC.jLabelXLeft(10,-290, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img8.png")));
                                 AC.jLabelYDown(-370, 70, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=8;
                                 break;
                      case 8 :   Thread.sleep(2000);
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYUp(70,-370, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img9.png")));
                                 AC.jLabelYUp(480, 70, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3,3,3,3, new java.awt.Color(0, 0, 0)));
                                 c=9;
                                 break;
                      case 9 :   Thread.sleep(2000);
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYDown(70,480, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img10.png")));
                                 AC.jLabelXRight(-290, 10, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=10;
                                 break;
                      case 10 :  Thread.sleep(2000);
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelXLeft(10,-290, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img11.png")));
                                 AC.jLabelYDown(-370, 70, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=11;
                                 break;
                      case 11 :  Thread.sleep(2000); 
                                 jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYUp(70,-370, 10, 10, jLabel9);
                                 jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img12.png")));
                                 AC.jLabelYUp(480, 70, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3,3,3,3, new java.awt.Color(0, 0, 0)));
                                 c=12;
                                 break;
                      case 12 :  Thread.sleep(2000);
                                 jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
                                 AC.jLabelYDown(70,480, 10, 10, jLabel8);
                                 jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,0,0, new java.awt.Color(0, 0, 0)));
                                 jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/img1.png")));
                                 AC.jLabelXRight(-290, 10, 10, 10, jLabel7);
                                 jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
                                 c=1;
                                 break;
                       
                  }      
                }
            }
            catch(Exception e) {
                
            }
            }
        }.start();
    }//GEN-LAST:event_jFrame1WindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        String name;
        char roomchr;
        name ="";
        roomchr=' ';
        String room="";
        int occp,days;
        long num;
        occp =days=0;
        num =0;
        float rPrice=0,price=0;
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM CHECKIN WHERE user = '"+user+"' AND pass = '"+pass+"'");
            if(res.next())
            {
            name =res.getString("name");
            roomchr = res.getString("roomchar").charAt(0);
            occp =res.getInt("occp");
            num=longValue(res.getBigDecimal("PHNUM"));
            days =res.getInt("days");
            }
        switch(roomchr)
        {
            case 'A' : room= "One Bedroom Suite";
                     break;
            case 'B' : room = "Deluxe One Bedroom Suite";
                     break;
            case 'C' : room = "Two Bedroom Suite";
                     break;         
            case 'D' : room = "Deluxe Two Bedroom Suite";
                     break;
            case 'E' : room = "Emirates Deluxe Suite";
                     break;
            case 'F' : room = "Royal Suite";
                     break;  
            case 'U' : room = "Two Bedroom Underwater Suite";
                     break;
        }
        switch(roomchr)
        {
            case 'A' : rPrice=800;
                     break;
            case 'B' : rPrice = 1000;
                     break;
            case 'C' : rPrice = 950;
                     break;         
            case 'D' : rPrice=1200;
                     break;
            case 'E' : rPrice = 3000;
                     break;
            case 'F' : rPrice= 3500;
                     break;  
            case 'U' : rPrice=5000;
                     break;
        }
        }
        catch(Exception e)
        {
        }
        price = rPrice*days;
        model.addColumn("");
        model.addColumn("Details");
        model.addRow(new Object[]{"Name",name});
        model.addRow(new Object[]{"No.Of Occupants ",occp});
        model.addRow(new Object[]{"Contact Number",num});
        model.addRow(new Object[]{"Suite Type",room});
        model.addRow(new Object[]{"No. of Days ",days});
        model.addRow(new Object[]{room,rPrice});
        model.addRow(new Object[]{days+" Days ",price+" AED"});
        model.addRow(new Object[]{"Total Room Rental : ",price});
        checkPrice = price;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        int a1,a2,a3,a4,a5,a6,a7,a8;
        a1=a2=a3=a4=a5=a6=a7=a8=0;
        float p1,p2,p3,p4,p5,p6,p7,p8;
        p1=p2=p3=p4=p5=p6=p7=p8=0;
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM ACTIVITY WHERE user = '"+user+"' AND pass = '"+pass+"'");
            if(res.next())
            {
            a1 =res.getInt("a1");
            a2 =res.getInt("a2");
            a3 =res.getInt("a3");
            a4 =res.getInt("a4");
            a5 =res.getInt("a5");
            a6 =res.getInt("a6");
            a7 =res.getInt("a7");
            a8 =res.getInt("a8");
            if(a1 == 1)
                p1=400;
            if(a2 == 1)
                p2=200;
            if(a3 == 1)
                p3=2000;
            if(a4 == 1)
                p4=700;
            if(a5 == 1)
                p5=1000;
            if(a6 == 1)
                p6=300;
            if(a7 == 1)
                p7=2500;
            if(a8 == 1)
                p8=500;
            }
        
        
        }
        catch(Exception e)
        {
        }
       model.addColumn("Activities");
        model.addColumn("Details");
        model.addColumn("Price");
        if(a1==1)
        model.addRow(new Object[]{"Al-Muntaha Restaurant","✓",p1+" AED"});
        else
            model.addRow(new Object[]{"Al-Muntaha Restaurant","✕"});
        if(a2==1)
        model.addRow(new Object[]{"24/7 Butler Service","✓",p2+" AED"});
        else
            model.addRow(new Object[]{"24/7 Butler Service","✕"});
        if(a3==1)
        model.addRow(new Object[]{"Dream Car Rental","✓",p3+" AED"});
        else
            model.addRow(new Object[]{"Dream Car Rental","✕"});
        if(a4==1)
        model.addRow(new Object[]{"Talise Fitness Club","✓",p4+" AED"});
        else
            model.addRow(new Object[]{"Talise Fitness Club","✕"});
        if(a5==1)
        model.addRow(new Object[]{"Helicopter Pickup","✓",p5+" AED"});
        else
            model.addRow(new Object[]{"Helicopter Pickup","✕"});
        if(a6==1)
        model.addRow(new Object[]{"Snooker Table In Suites","✓",p6+" AED"});
        else
            model.addRow(new Object[]{"Snooker Table In Suites","✕"});
        if(a7==1)
        model.addRow(new Object[]{"Personal Yacht Sightseeing","✓",p7+" AED"});
        else
            model.addRow(new Object[]{"Personal Yacht Sightseeing","✕"});
        if(a8==1)
        model.addRow(new Object[]{"Wild Wadi Waterpark","✓",p8+" AED"});
        else
            model.addRow(new Object[]{"Wild Wadi Waterpark","✕"});
       actPrice=p1+p2+p3+p4+p5+p6+p7+p8;
        model.addRow(new Object[]{"Total Activities Price",actPrice+" AED"});
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("");
        model.addColumn("Price");
        String name="";
        int cabno=0,num=0;
        String cabclass="",hosclass="",exfacil="";
        float cabp,hosp,exfacp,hourp,roy,ser,tot;
        cabp=hosp=exfacp=hourp=roy=ser=tot=0;
       
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM TERRACE WHERE user = '"+user+"' AND pass = '"+pass+"'");
            if(res.next())
            { cabclass=res.getString("cabclass");
              hosclass= res.getString("hosclass");
              exfacil=res.getString("exfacil");
              cabno=res.getInt("cabno");
              num=res.getInt("hour");
              cabp=res.getInt("cabprice");
              hosp=res.getInt("hosprice");
              exfacp=res.getInt("exfacprice");
              roy=res.getInt("roytax");
              ser=res.getInt("sertax");
            }
            tot=cabp+hosp+exfacp+(num*100)+roy+ser;
        model.addRow(new Object[]{cabclass,cabp+" AED"});
        model.addRow(new Object[]{"Cabana No.",cabno});
        model.addRow(new Object[]{hosclass,hosp+" AED"});
        model.addRow(new Object[]{exfacil,exfacp+" AED"});
        model.addRow(new Object[]{num+" Hours",(num*100)+" AED"});
        model.addRow(new Object[]{"Royalty Tax",roy+" AED"});
        model.addRow(new Object[]{"Service Tax :",ser+" AED"});
        model.addRow(new Object[]{"Total Cabana Price:",tot+" AED"});
        terrPrice=tot;
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("");
        model.addColumn("Destination");
        model.addColumn("Price");
        String cl,w,s,m,r,k,spo;
        cl=w=s=m=r=k=spo="";
        int wp,sp,mp,rp,kp,spp,tot;
        wp=sp=mp=rp=kp=spp=tot=0;
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM TOURISM WHERE user = '"+user+"' AND pass = '"+pass+"'");
            if(res.next())
            {
                cl=res.getString("class");
                w=res.getString("world");
                s=res.getString("sight");
                m=res.getString("mall");
                r=res.getString("resort");
                k=res.getString("kids");
                spo=res.getString("sports");
                tot=res.getInt("price");
                wp=res.getInt("wprice");
                sp=res.getInt("sprice");
                mp=res.getInt("mprice");
                rp=res.getInt("rprice");
                kp=res.getInt("kprice");
                spp=res.getInt("soprice");
            }
            model.addRow(new Object[]{"Package Class :",cl,null});
            model.addRow(new Object[]{"World Landmark :",w,wp+" AED"});
            model.addRow(new Object[]{"Sightseeing Spot :",s,sp+" AED"});
            model.addRow(new Object[]{"Mall :",m,mp+" AED"});
            model.addRow(new Object[]{"Resort :",r,rp+" AED"});
            model.addRow(new Object[]{"Kids Spot :",k,kp+" AED"});
            model.addRow(new Object[]{"Sports :",spo,spp+" AED"});
            model.addRow(new Object[]{"Total Price :",null,tot+" AED"});
            tourPrice=tot;
            }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jFrame2.setVisible(true);
        finPrice=checkPrice+actPrice+terrPrice+tourPrice;
        System.out.println("Check Price "+checkPrice);
        System.out.println("Activity Price "+actPrice);
        System.out.println("Terrace Price "+terrPrice);
        System.out.println("Tourism Price "+tourPrice);
        jLabel12.setText(""+finPrice+" AED");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex()==0)
        {
            conPrice= 0.27f* finPrice;
            jLabel15.setText(conPrice+" USD");
        }
        if(jComboBox1.getSelectedIndex()==1)
        {
            conPrice= 22.38f* finPrice;
            jLabel15.setText(conPrice+" INR");
        }
        if(jComboBox1.getSelectedIndex()==2)
        {
            conPrice= 0.40f* finPrice;
            jLabel15.setText(conPrice+" AUD");
        }
        if(jComboBox1.getSelectedIndex()==3)
        {
            conPrice= 0.22f* finPrice;
            jLabel15.setText(conPrice+" GBP");
        }
        if(jComboBox1.getSelectedIndex()==4)
        {
            conPrice= 0.0000097f* finPrice;
            jLabel15.setText(conPrice+" BitCoins");
        }
        if(jComboBox1.getSelectedIndex()==5)
        {
            conPrice= 1.87f* finPrice;
            jLabel15.setText(conPrice+" CNY");
        }
        if(jComboBox1.getSelectedIndex()==6)
        {
            conPrice= 397.81f* finPrice;
            jLabel15.setText(conPrice+" IQD");
        }
        if(jComboBox1.getSelectedIndex()==7)
        {
            conPrice= 36.05f* finPrice;
            jLabel15.setText(conPrice+" JPY");
        }
        if(jComboBox1.getSelectedIndex()==8)
        {
            conPrice= 245.05f* finPrice;
            jLabel15.setText(conPrice+" KPW");
        }
        if(jComboBox1.getSelectedIndex()==9)
        {
            conPrice= 0.25f* finPrice;
            jLabel15.setText(conPrice+" CHF");
        }
        if(jComboBox1.getSelectedIndex()==10)
        {
            conPrice= 9.32f* finPrice;
            jLabel15.setText(conPrice+" THB");
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    public class time implements ActionListener {
        public void actionPerformed(ActionEvent e)
        {  
           if(time1 == 4)
           {
               jButton1.setForeground(new java.awt.Color(187, 187, 187));
               jButton1.setText("Checking!");
           }
            
            time1++;
           
        }
    } 
    public void setLayout()
    {
        
    }
    
    
    public class tech implements ActionListener {
       public void actionPerformed(ActionEvent e) {
          if(jLabel1.getX() == 20)
          { 
           String s,s1,s2="",s3;
           s="Burj Al Arab Customer Lounge";
           s1=jLabel1.getText();
           s2=s1.substring(i);
           s3=s.substring(0,i);
           jLabel1.setText(s3+s2);
           i++;
           s2=s3="";
           if(i==29)
           { 
               tech.stop();
               panel.start();
           }
          }
        }
     }
     
    public class Panel implements ActionListener{
    public void actionPerformed(ActionEvent evt) {
        if(red == 255 && green == 255 && blue == 255)
            ch = 1;
        if(red == 0 && green == 0 && blue == 0)
            ch = 0;
        Color();
        jPanel1.setBackground(new java.awt.Color(red, green, blue));
    }
    }
    public void Color(){
        if(ch == 0)
            if(red == 255)
        {
           if(blue==255 && red ==255)
           {
           blue =255;
           red=255;
           green++;          
           }
           else
           {   
            red= 255;
           blue++;
           }
        }
        else
            red++;
        if(ch == 1)
            if(green == 0)
        {
           if(green==0 && red ==0)
           {
           red =0;
           green=0;
           blue--;          
           }

           else
           {   
            green = 0;
           red--;
           }
        }
        else
            green--;
        
    }

    public static void hmm()  {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout1().setVisible(true);
              
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout1().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
