/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burjalarab_techno;

/**
 *
 * @author Sony
 */
import AppPackage.AnimationClass;
import static burjalarab_techno.Activities1.user;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
public class TheTerrace1 extends javax.swing.JFrame {

    /**
     * Creates new form TheTerrace
     */
    public TheTerrace1() {
        initComponents();
    }
    static int cabno;
    float totprice = 0;
    String namelabel="";
    float roy,ser;
    float cabp,hosp,exfacp,roytax,sertax=0;
    static String name = "",room = "";
    static String hour="",cabclass="",hosclass="",exfacil="";
    static int hours=0,cabcl =0,hoscl = 0,exfac=0;
    static String user = "",pass = "";
    static int ch=0, ch1 = 0;
    static int red = 0,green =0,blue=0,r=0,g=0,b=0;
    Timer timer=new Timer(25,new tech());
    Timer panel = new Timer(50,new Panel());
    int[] price = new int[4];
    Timer panel1 = new Timer(50,new Panel1());
    public DefaultTableModel m ;
    public class Panel implements ActionListener{
    public void actionPerformed(ActionEvent evt) {
        Color();
        if(red == 255 && green == 255 && blue == 255)
            ch1 = 1;
        if(red == 0 && green == 0 && blue == 0)
            ch1 = 0;
        jPanel3.setBackground(new java.awt.Color(red, green, blue));
    }
    }
    public class Panel1 implements ActionListener{
    public void actionPerformed(ActionEvent evt) {
        Color1();
        if(r == 255 && g == 255 && b == 255)
            ch = 1;
        if(r == 0 && g == 0 && b== 0)
            ch = 0;
        jPanel1.setBackground(new java.awt.Color(r, g,b));
    }
    }
    public void Color1(){
        if(ch == 0)
            if(r == 255)
        {
           if(r==255 && b ==255)
           {
           r =255;
           b=255;
           g++;          
           }
           else
           {   
            r= 255;
           b++;
           }
        }
        else
            r++;
        if(ch == 1)
            if(b == 0)
        {
           if(b==0 && r ==0)
           {
           b =0;
           r=0;
           g--;          
           }
           else
           {   
            b = 0;
           r--;
           }
        }
        else
            b--;
        
    }
    public void Color(){
        if(ch1 == 0)
            if(blue == 255)
        {
           if(blue==255 && red ==255)
           {
           blue =255;
           red=255;
           green++;          
           }
           else
           {   
            blue= 255;
           red++;
           }
        }
        else
            blue++;
        if(ch1 == 1)
            if(green == 0)
        {
           if(green==0 && blue ==0)
           {
           green =0;
           blue=0;
           red--;          
           }
           else
           {   
            green = 0;
           blue--;
           }
        }
        else
            green--;
        
    }
    public class tech implements ActionListener {
    public void actionPerformed(ActionEvent evt){
        int n = jProgressBar1.getValue();
       if(n<100)
       {   n++;
           jProgressBar1.setValue(n);
           
       }
       else{ 
           timer.stop();
           jLabel23.setForeground(new java.awt.Color(51,201, 51));
           jLabel23.setText("Cabana Available!");
           int num= 10;
           for(int n2=1;n2<30;n2++){
              num = (int)(Math.random()* 100);
              if(num < 35 && num>0)
                  break;
              else continue;
           }
           cabno= num;
           jLabel24.setText("Cabana No. "+ num);
           jButton3.setEnabled(true);
           jButton3.setText(" Proceed ");
       }
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setMinimumSize(new java.awt.Dimension(517, 270));
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("CordiaUPC", 1, 36)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Assigning Cabana.....");

        jLabel24.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setFont(new java.awt.Font("CordiaUPC", 3, 24)); // NOI18N
        jButton3.setText("Waiting!");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(627, 541));
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame1WindowOpened(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("CordiaUPC", 1, 36)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("The Terrace ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selection", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel30.setFont(new java.awt.Font("CordiaUPC", 3, 36)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel31.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("*Includes 10% Royalty Tax And 15% Service Tax");

        jButton4.setFont(new java.awt.Font("CordiaUPC", 1, 24)); // NOI18N
        jButton4.setText("Book Your Cabana");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("CordiaUPC", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Total Price");

        jLabel33.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 850));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Terrace");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 1146, 60);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terraceM3.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(312, 107, 400, 440);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terrace1.PNG"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 830, 168, 180);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terrace2.PNG"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(204, 830, 168, 182);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terrace3.PNG"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(396, 830, 168, 182);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terrace4.PNG"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(588, 830, 168, 182);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terrace5.PNG"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(780, 830, 168, 186);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terraceM7.PNG"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(972, 830, 168, 182);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Set in the stunning azure waters of the Arabian Gulf, discover the highly anticipated Burj Al Arab Terrace. Located at Dubai’s most iconic hotel, the terrace is a remarkable, one-of-a-kind restaurant, pool, beach and cabana space, offering hotel guests and Burj Al Arab members the finest Arabian hospitality.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 290, 440);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel25.setFont(new java.awt.Font("CordiaUPC", 3, 36)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("The Terrace");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Book Your Exotic Cabana In The Burj Al Arab Terrace");

        jLabel27.setFont(new java.awt.Font("CordiaUPC", 3, 24)); // NOI18N
        jLabel27.setText("User ID");

        jLabel28.setFont(new java.awt.Font("CordiaUPC", 3, 24)); // NOI18N
        jLabel28.setText("Password");

        jTextField4.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("CordiaUPC", 3, 24)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("CordiaUPC", 0, 24)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextField4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4))
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 410, 440);

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Book Your Cabana Now!");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(6, 6, 380, 49);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Name : ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 60, 170, 34);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Room Number :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 110, 170, 34);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setText("Cabana Class :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 150, 170, 35);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("Hospitality Class :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 200, 170, 36);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Extra Facilities : ");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 270, 170, 35);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 240, 380, 24);

        jButton1.setFont(new java.awt.Font("CordiaUPC", 3, 24)); // NOI18N
        jButton1.setText("Book Now!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 360, 380, 60);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 60, 204, 34);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 110, 204, 34);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Cabana", "Luxury Cabana", "Emirates Class" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(180, 150, 204, 35);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Package", "Special Package", "Royal Package" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(180, 200, 204, 36);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jet Skiing", "Flyboarding", "Kite Surfing", "Surf Boarding", "Sp. Volleyball Court", "Yatching" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(180, 270, 201, 35);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setText("No. Of Hours :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 310, 170, 36);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(180, 310, 201, 36);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(724, 107, 400, 428);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 561, 1164, 10);

        jLabel9.setFont(new java.awt.Font("Cordia New", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Terrace");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 580, 192, 32);

        jLabel10.setFont(new java.awt.Font("Cordia New", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Restaurant");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(192, 580, 192, 32);

        jLabel11.setFont(new java.awt.Font("Cordia New", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pools");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(384, 580, 192, 32);

        jLabel12.setFont(new java.awt.Font("Cordia New", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cabanas ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(576, 580, 192, 32);

        jLabel13.setFont(new java.awt.Font("Cordia New", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Luxury");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(768, 580, 192, 32);

        jLabel14.setFont(new java.awt.Font("Cordia New", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Elegance");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(960, 580, 192, 32);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 80, 1170, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(960, 562, 30, 130);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(192, 562, 10, 130);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(384, 562, 30, 130);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(576, 562, 30, 130);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(768, 562, 30, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terraceM3.PNG")));
        jTextArea1.setText("Set in the stunning azure waters of the Arabian Gulf, discover the highly anticipated Burj Al Arab Terrace. Located at Dubai’s most iconic hotel, the terrace is a remarkable, one-of-a-kind restaurant, pool, beach and cabana space, offering hotel guests and Burj Al Arab members the finest Arabian hospitality.");
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terraceM2.PNG")));
        jTextArea1.setText("Perched on Burj Al Arab Terrace and extending over the Arabian Gulf, the restaurant and bar present a new and unseen perspective of the hotel, as well as an inventive take on social dining. The menu features a novel blend of ingredients, drawing inspiration from Latin America, the Mediterranean and Asia to deliver rippling flavours in a style that can be described as casually gourmet. ");
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/ter1.PNG")));
        jTextArea1.setText("The 24 Cabanas and eight Royal Cabanas can accommodate up to four people, offering unrivalled poolside facilities - dedicated butler service, a dining, beverage and bar menu, spa menu, fully stocked mini-bars, fresh fruit, espresso machines, Bang & Olufsen TVs and a rotating amenity cycle with 4 – 6 varieties per day. The eight Royal Cabanas also include a private bathroom and shower area as well as a veranda overlooking the sea.");
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/ter2.PNG")));
        jTextArea1.setText("A breakthrough combination of creative marine design, ingenious engineering and guest-friendly planning, the terrace was built offshore in Finland and transported to Dubai by sea. The private 10,000 square metre outdoor luxury leisure facility now seamlessly stretches 100 metres out into the sea and is home to Scape Restaurant & Bar, two stunning pools, dedicated butler-serviced cabanas, and a beach area with luxury day and sunbeds.");
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terraceM7.PNG")));
        jTextArea1.setText("Burj Al Arab Terrace has been developed using state-of-the-art environmental technology, design, manufacturing expertise and marine installation mastery, a combination which has never before been attempted. The 10,000 square metres private luxury terrace fans 100 metres out into the Arabian Gulf and accommodates 32 cabanas, 400 sun loungers, one fresh water pool measuring 612 square metres and one salt water pool measuring 828 square metres as well as Scape Restaurant & Bar.");
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burjalarab_techno/terraceM5.PNG")));
        jTextArea1.setText("The two impressive pools on Burj Al Arab Terrace are ideal for relaxing, cooling down and soaking up the Arabian sun within plush surroundings. The fresh water pool spans over 612 square metre with a shaded swim up bar at its centre, setting the perfect tone for either relaxing or socialising. The 828 square metre salt water infinity pool appears to seamlessly blend with the sea. With four Jacuzzis, a picturesque vantage and a stretch of sand it makes for a truly treasurable experience by the water.");
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        switch(jComboBox2.getSelectedIndex())
        {
            case 0 :  jLabel21.setText("*Includes Pool Access, Regular Cuisine And Drinks!");
                      break;
            case 1 :  jLabel21.setText("*Includes Crystal Pool Access and Continental Cuisine!");
                      break;
            case 2 : jLabel21.setText("*Includes Crystal Pool Access, Royal Cuisine And Exotic Drinks!");
            break;
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened
           timer.start();
    }//GEN-LAST:event_jDialog1WindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialog1.setVisible(true);
        jDialog1.setSize(517,200);
        name =jTextField1.getText();
        room = jTextField2.getText();
        cabcl = jComboBox1.getSelectedIndex();
        hoscl = jComboBox2.getSelectedIndex();
        exfac = jComboBox3.getSelectedIndex();
        hours = jComboBox4.getSelectedIndex();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AnimationClass AC = new AnimationClass();
        if(true)
        {   
        AC.jLabelYUp(830, 620, 10, 10, jLabel3);
        AC.jLabelYUp(830, 620, 10, 10, jLabel4);
        AC.jLabelYUp(830, 620, 10, 10, jLabel5);
        AC.jLabelYUp(830, 620, 10, 10, jLabel6);
        AC.jLabelYUp(830, 620, 10, 10, jLabel7);
        AC.jLabelYUp(830, 620, 10, 10, jLabel8);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        jFrame1.setVisible(true);
        name = jTextField1.getText();
        room = jTextField2.getText();
        cabcl = jComboBox1.getSelectedIndex();
        hoscl = jComboBox2.getSelectedIndex();
        hours = jComboBox4.getSelectedIndex();
        jLabel30.setText("Welcome Mr. "+namelabel);
        switch(cabcl)
        {
                case 0 :model.addRow(new Object[]{"Regular Cabana","2500 AED"});
                cabclass = "Regular Cabana";
                price[0] = 2500;
                break;
                case 1 :model.addRow(new Object[]{"Luxury Cabana","3750 AED"});
                cabclass = "Luxury Cabana";
                price[0] = 3750;
                break;
                case 2 :model.addRow(new Object[]{"Emirates Cabana","5000 AED"});
                cabclass = "Emirates Cabana";
                price[0] = 5000;
                break;
        }
        switch(hoscl)
        {
                case 0 :model.addRow(new Object[]{"Regular Package","550 AED"});
                hosclass = "Regular Package";
                price[1] = 550;
                break;
                case 1 :model.addRow(new Object[]{"Special Package","900 AED"});
                hosclass = "Special Package";
                price[1] = 900;
                break;
                case 2 :model.addRow(new Object[]{"Royal Package","1500 AED"});
                hosclass = "Royal Package";
                price[1] = 1500;
                break;
        }
        switch(exfac)
        {
                case 0 :model.addRow(new Object[]{"Jet Skiing","600 AED"});
                exfacil = "Jet Skiing";
                price[2] = 600;
                break;
                case 1 :model.addRow(new Object[]{"Flyboarding","1000 AED"});
                exfacil = "Flyboarding";
                price[2] = 1000;
                break;
                case 2 :model.addRow(new Object[]{"Kite Surfing","500 AED"});
                exfacil = "Kite Surfing";
                price[2] = 1300;
                break;
                case 3 :model.addRow(new Object[]{"Surf Boarding","700 AED"});
                exfacil = "Surf Boarding";
                price[2] = 1300;
                break;
                case 4 :model.addRow(new Object[]{"Sp. Volleyball Court","450 AED"});
                exfacil = "SP. Volleyball Court";
                price[2] = 1300;
                break;
                case 5 :model.addRow(new Object[]{"Yatching","900 AED"});
                exfacil = "Yatching";
                price[2] = 1300;
                break;
        }
        switch(hours)
        {
                case 1 :model.addRow(new Object[]{"One Hour","100 AED"});
                hour="1";
                price[3] = 100;
                break;
                case 2 :model.addRow(new Object[]{"Two Hours","200 AED"});
                hour="2";
                price[3] = 200;
                break;
                case 3 :model.addRow(new Object[]{"Three Hours","300 AED"});
                hour="3";
                price[3] = 300;
                break;
                case 4 :model.addRow(new Object[]{"Four Hours","400 AED"});
                price[3] = 400;
                hour="4";
                break;
                case 5 :model.addRow(new Object[]{"Five Hours","500 AED"});
                price[3] = 500;
                hour="5";
                break;
                case 6 :model.addRow(new Object[]{"Six Hours","600 AED"});
                price[3] = 600;
                hour="6";
                break;
                case 7 :model.addRow(new Object[]{"Seven Hours","700 AED"});
                price[3] = 700;
                hour="7";
                break;
                case 8 :model.addRow(new Object[]{"Eight Hours","800 AED"});
                price[3] = 800;
                hour="8";
                break;
                case 9 :model.addRow(new Object[]{"Nine Hours","900 AED"});
                price[3] = 900;
                hour="9";
                break;
                case 10 :model.addRow(new Object[]{"Ten Hours","1000 AED"});
                price[3] = 1000;
                hour="10";
                break;
        }
        
        for(int i =0;i<4;i++)
            totprice += price[i];
        cabp=price[0];
        hosp=price[1];
        exfacp=price[2];
        roy = totprice * 15f/100;
        ser = totprice * 10f/100;
        model.addRow(new Object[]{"Royalty Tax",""+roy+" AED"});
        model.addRow(new Object[]{"Service Tax",""+ser+" AED"});
        totprice = totprice + roy +ser;
        jLabel33.setText(""+(int)totprice+" AED");
        jLabel30.setText("Welcome Mr. "+ name);
        m=model;
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta1 = con.createStatement();
            int i = sta1.executeUpdate("INSERT INTO TERRACE VALUES ('"+user+"','"+pass+"','"+cabclass+"','"+hosclass+"','"+exfacil+"',"+hour+","+cabno+","+ser+","+roy+","+exfacp+","+hosp+","+cabp+","+totprice+")");
            if(i > 0) {
                JOptionPane.showMessageDialog(null,"Your Cabana is Booked... For Time Details and more information, contact Bell Desk at Your Floor or at the Reception. ");
                jButton4.setText("Booked!");
                jButton4.setForeground(new java.awt.Color(51, 201, 51));
                jButton4.setEnabled(false);
            }
            else 
                JOptionPane.showMessageDialog(null," System Error.... ");
               
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,e);  
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jFrame1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowOpened
        panel.start();
    }//GEN-LAST:event_jFrame1WindowOpened

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        user = jTextField5.getText();
        pass = jTextField4.getText();
        AnimationClass AC  = new AnimationClass();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/burjalarab","root","techno");
            Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery("SELECT * FROM CHECKIN WHERE user = '"+user+"' AND pass = '"+pass+"'");
            if(res.next())
            {
                jPanel2.setVisible(false);
                panel1.start();
            }namelabel = res.getString("name");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheTerrace1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheTerrace1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheTerrace1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheTerrace1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheTerrace1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
